export const affiliate_leaderboard = [
  {
    rank: 1,
    initials: "JW",
    name: "James Wilson",
    tier: "Diamond",
    portfolio: "£5.8M",
    income: "£72.5K",
    change: 18,
  },
  {
    rank: 2,
    initials: "ET",
    name: "Emily Thompson",
    tier: "Platinum",
    portfolio: "£4.2M",
    income: "£52.5K",
    change: 14,
  },
  {
    rank: 3,
    initials: "SJ",
    name: "You (Sarah Johnson)",
    tier: "Silver",
    portfolio: "£2.5M",
    income: "£25K",
    change: 22,
  },
  {
    rank: 4,
    initials: "RC",
    name: "Robert Chen",
    tier: "Silver",
    portfolio: "£2.1M",
    income: "£21K",
    change: 8,
  },
  {
    rank: 5,
    initials: "MG",
    name: "Maria Garcia",
    tier: "Bronze",
    portfolio: "£950K",
    income: "£9.5K",
    change: -3,
  },
];
