export const affiliate_leaderboard = [
  {
    rank: 1,
    initials: "JW",
    name: "James Wilson",
    tier: "Vintage Associate",
    portfolio: "£5.8M",
    income: "£72.5K",
    change: 18,
  },
  {
    rank: 2,
    initials: "ET",
    name: "Emily Thompson",
    tier: "Vintage Enclosure",
    portfolio: "£4.2M",
    income: "£52.5K",
    change: 14,
  },
  {
    rank: 3,
    initials: "SJ",
    name: "You (Sarah Johnson)",
    tier: "Vintage Cru",
    portfolio: "£2.5M",
    income: "£25K",
    change: 22,
  },
  {
    rank: 4,
    initials: "RC",
    name: "Robert Chen",
    tier: "Vintage Cru",
    portfolio: "£2.1M",
    income: "£21K",
    change: 8,
  },
  {
    rank: 5,
    initials: "MG",
    name: "Maria Garcia",
    tier: "Vintage",
    portfolio: "£950K",
    income: "£9.5K",
    change: -3,
  },
  {
    rank: 6,
    initials: "JL",
    name: "James Lee",
    tier: "Vintage",
    portfolio: "£930K",
    income: "£9.3K",
    change: -1,
  },
  {
    rank: 7,
    initials: "SW",
    name: "Sarah Wilson",
    tier: "Vintage",
    portfolio: "£920K",
    income: "£9.2K",
    change: -2,
  },
  {
    rank: 8,
    initials: "DT",
    name: "David Thompson",
    tier: "Vintage",
    portfolio: "£910K",
    income: "£9.1K",
    change: 0,
  },
  {
    rank: 9,
    initials: "KH",
    name: "Karen Hall",
    tier: "Vintage",
    portfolio: "£900K",
    income: "£9.0K",
    change: 1,
  },
  {
    rank: 10,
    initials: "AM",
    name: "Andrew Martinez",
    tier: "Vintage",
    portfolio: "£890K",
    income: "£8.9K",
    change: 2,
  },
  {
    rank: 11,
    initials: "CB",
    name: "Chloe Brown",
    tier: "Vintage",
    portfolio: "£880K",
    income: "£8.8K",
    change: -1,
  },
  {
    rank: 12,
    initials: "RS",
    name: "Robert Scott",
    tier: "Vintage",
    portfolio: "£870K",
    income: "£8.7K",
    change: 1,
  },
  {
    rank: 13,
    initials: "LP",
    name: "Laura Perez",
    tier: "Vintage",
    portfolio: "£860K",
    income: "£8.6K",
    change: -2,
  },
  {
    rank: 14,
    initials: "DN",
    name: "Daniel Nguyen",
    tier: "Vintage",
    portfolio: "£850K",
    income: "£8.5K",
    change: 0,
  },
  {
    rank: 15,
    initials: "EH",
    name: "Emily Harris",
    tier: "Vintage",
    portfolio: "£840K",
    income: "£8.4K",
    change: -3,
  },
  {
    rank: 16,
    initials: "MB",
    name: "Michael Baker",
    tier: "Vintage",
    portfolio: "£830K",
    income: "£8.3K",
    change: 2,
  },
  {
    rank: 17,
    initials: "SS",
    name: "Stephanie Smith",
    tier: "Vintage",
    portfolio: "£820K",
    income: "£8.2K",
    change: -1,
  },
  {
    rank: 18,
    initials: "WB",
    name: "William Bell",
    tier: "Vintage",
    portfolio: "£810K",
    income: "£8.1K",
    change: 1,
  },
  {
    rank: 19,
    initials: "CR",
    name: "Catherine Ross",
    tier: "Vintage",
    portfolio: "£800K",
    income: "£8.0K",
    change: 0,
  },
  {
    rank: 20,
    initials: "JP",
    name: "Joshua Price",
    tier: "Vintage",
    portfolio: "£790K",
    income: "£7.9K",
    change: -2,
  },
  {
    rank: 21,
    initials: "EO",
    name: "Elizabeth Owens",
    tier: "Vintage",
    portfolio: "£780K",
    income: "£7.8K",
    change: 1,
  },
  {
    rank: 22,
    initials: "TM",
    name: "Thomas Murphy",
    tier: "Vintage",
    portfolio: "£770K",
    income: "£7.7K",
    change: -1,
  },
  {
    rank: 23,
    initials: "AR",
    name: "Amy Rogers",
    tier: "Vintage",
    portfolio: "£760K",
    income: "£7.6K",
    change: 0,
  },
  {
    rank: 24,
    initials: "GH",
    name: "George Howard",
    tier: "Vintage",
    portfolio: "£750K",
    income: "£7.5K",
    change: -3,
  },
  {
    rank: 25,
    initials: "NB",
    name: "Natalie Brooks",
    tier: "Vintage",
    portfolio: "£740K",
    income: "£7.4K",
    change: 2,
  }
];
